//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacEleUtils.DoceleOLService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.facele.cl/DoceleOL/", ConfigurationName="DoceleOLService.DoceleOL")]
    public interface DoceleOL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/generaDTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.generaDTEResponse generaDTE(FacEleUtils.DoceleOLService.generaDTERequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/generaDTE", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.generaDTEResponse> generaDTEAsync(FacEleUtils.DoceleOLService.generaDTERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/obtieneDTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.obtieneDTEResponse obtieneDTE(FacEleUtils.DoceleOLService.obtieneDTERequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/obtieneDTE", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.obtieneDTEResponse> obtieneDTEAsync(FacEleUtils.DoceleOLService.obtieneDTERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/sinConfirmar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.sinConfirmarResponse sinConfirmar(FacEleUtils.DoceleOLService.sinConfirmarRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/sinConfirmar", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.sinConfirmarResponse> sinConfirmarAsync(FacEleUtils.DoceleOLService.sinConfirmarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/controversia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.controversiaResponse controversia(FacEleUtils.DoceleOLService.controversiaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/controversia", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.controversiaResponse> controversiaAsync(FacEleUtils.DoceleOLService.controversiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/obtieneBorrador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.obtieneBorradorResponse obtieneBorrador(FacEleUtils.DoceleOLService.obtieneBorradorRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/obtieneBorrador", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.obtieneBorradorResponse> obtieneBorradorAsync(FacEleUtils.DoceleOLService.obtieneBorradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/reimprimeDTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacEleUtils.DoceleOLService.reimprimeDTEResponse reimprimeDTE(FacEleUtils.DoceleOLService.reimprimeDTERequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.facele.cl/DoceleOL/reimprimeDTE", ReplyAction="*")]
        System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.reimprimeDTEResponse> reimprimeDTEAsync(FacEleUtils.DoceleOLService.reimprimeDTERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.facele.cl/DoceleOL/")]
    public enum generaDTEFormato {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        TXT,
        
        /// <remarks/>
        TXT123,
        
        /// <remarks/>
        XML_OBS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generaDTE", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class generaDTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacEleUtils.DoceleOLService.generaDTEFormato formato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid;
        
        public generaDTERequest() {
        }
        
        public generaDTERequest(string rutEmisor, int tipoDTE, FacEleUtils.DoceleOLService.generaDTEFormato formato, string txt, string xml, string uuid) {
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.formato = formato;
            this.txt = txt;
            this.xml = xml;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generaDTEResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class generaDTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folioDTE;
        
        public generaDTEResponse() {
        }
        
        public generaDTEResponse(int estadoOperacion, string descripcionOperacion, string rutEmisor, int tipoDTE, long folioDTE) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.folioDTE = folioDTE;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.facele.cl/DoceleOL/")]
    public enum obtieneDTEFormato {
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        PDF_TERMICO,
        
        /// <remarks/>
        URL_PDF,
        
        /// <remarks/>
        PDF_2N,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtieneDTE", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class obtieneDTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folioDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacEleUtils.DoceleOLService.obtieneDTEFormato formato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool cedible;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public obtieneDTERequest() {
        }
        
        public obtieneDTERequest(string rutEmisor, int tipoDTE, long folioDTE, FacEleUtils.DoceleOLService.obtieneDTEFormato formato, bool cedible, int cantidad) {
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.folioDTE = folioDTE;
            this.formato = formato;
            this.cedible = cedible;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtieneDTEResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class obtieneDTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] PDF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL;
        
        public obtieneDTEResponse() {
        }
        
        public obtieneDTEResponse(int estadoOperacion, string descripcionOperacion, string XML, byte[] PDF, string URL) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
            this.XML = XML;
            this.PDF = PDF;
            this.URL = URL;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.facele.cl/DoceleOL/")]
    public partial class Documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutEmisorField;
        
        private int tipoDTEField;
        
        private long folioDTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rutEmisor {
            get {
                return this.rutEmisorField;
            }
            set {
                this.rutEmisorField = value;
                this.RaisePropertyChanged("rutEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tipoDTE {
            get {
                return this.tipoDTEField;
            }
            set {
                this.tipoDTEField = value;
                this.RaisePropertyChanged("tipoDTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long folioDTE {
            get {
                return this.folioDTEField;
            }
            set {
                this.folioDTEField = value;
                this.RaisePropertyChanged("folioDTE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sinConfirmar", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class sinConfirmarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool iniciaProceso;
        
        public sinConfirmarRequest() {
        }
        
        public sinConfirmarRequest(bool iniciaProceso) {
            this.iniciaProceso = iniciaProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sinConfirmarResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class sinConfirmarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadDocumentos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("Documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacEleUtils.DoceleOLService.Documento[] Documento;
        
        public sinConfirmarResponse() {
        }
        
        public sinConfirmarResponse(int estadoOperacion, string descripcionOperacion, int cantidadDocumentos, FacEleUtils.DoceleOLService.Documento[] Documento) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
            this.cantidadDocumentos = cantidadDocumentos;
            this.Documento = Documento;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.facele.cl/DoceleOL/")]
    public enum controversiaOperacion {
        
        /// <remarks/>
        libera,
        
        /// <remarks/>
        anula,
        
        /// <remarks/>
        confirma,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controversia", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class controversiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folioDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacEleUtils.DoceleOLService.controversiaOperacion operacion;
        
        public controversiaRequest() {
        }
        
        public controversiaRequest(string rutEmisor, int tipoDTE, long folioDTE, FacEleUtils.DoceleOLService.controversiaOperacion operacion) {
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.folioDTE = folioDTE;
            this.operacion = operacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controversiaResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class controversiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        public controversiaResponse() {
        }
        
        public controversiaResponse(int estadoOperacion, string descripcionOperacion) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.facele.cl/DoceleOL/")]
    public enum FormatoType {
        
        /// <remarks/>
        TXT,
        
        /// <remarks/>
        TXT123,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        XML_OBS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtieneBorrador", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class obtieneBorradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacEleUtils.DoceleOLService.FormatoType formato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xml;
        
        public obtieneBorradorRequest() {
        }
        
        public obtieneBorradorRequest(string rutEmisor, int tipoDTE, FacEleUtils.DoceleOLService.FormatoType formato, string txt, string xml) {
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.formato = formato;
            this.txt = txt;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtieneBorradorResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class obtieneBorradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] PDF;
        
        public obtieneBorradorResponse() {
        }
        
        public obtieneBorradorResponse(int estadoOperacion, string descripcionOperacion, byte[] PDF) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
            this.PDF = PDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reimprimeDTE", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class reimprimeDTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long folioDTE;
        
        public reimprimeDTERequest() {
        }
        
        public reimprimeDTERequest(string rutEmisor, int tipoDTE, long folioDTE) {
            this.rutEmisor = rutEmisor;
            this.tipoDTE = tipoDTE;
            this.folioDTE = folioDTE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reimprimeDTEResponse", WrapperNamespace="http://www.facele.cl/DoceleOL/", IsWrapped=true)]
    public partial class reimprimeDTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estadoOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.facele.cl/DoceleOL/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionOperacion;
        
        public reimprimeDTEResponse() {
        }
        
        public reimprimeDTEResponse(int estadoOperacion, string descripcionOperacion) {
            this.estadoOperacion = estadoOperacion;
            this.descripcionOperacion = descripcionOperacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoceleOLChannel : FacEleUtils.DoceleOLService.DoceleOL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoceleOLClient : System.ServiceModel.ClientBase<FacEleUtils.DoceleOLService.DoceleOL>, FacEleUtils.DoceleOLService.DoceleOL {
        
        public DoceleOLClient() {
        }
        
        public DoceleOLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoceleOLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoceleOLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoceleOLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.generaDTEResponse FacEleUtils.DoceleOLService.DoceleOL.generaDTE(FacEleUtils.DoceleOLService.generaDTERequest request) {
            return base.Channel.generaDTE(request);
        }
        
        public int generaDTE(ref string rutEmisor, ref int tipoDTE, FacEleUtils.DoceleOLService.generaDTEFormato formato, string txt, string xml, string uuid, out string descripcionOperacion, out long folioDTE) {
            FacEleUtils.DoceleOLService.generaDTERequest inValue = new FacEleUtils.DoceleOLService.generaDTERequest();
            inValue.rutEmisor = rutEmisor;
            inValue.tipoDTE = tipoDTE;
            inValue.formato = formato;
            inValue.txt = txt;
            inValue.xml = xml;
            inValue.uuid = uuid;
            FacEleUtils.DoceleOLService.generaDTEResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).generaDTE(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            rutEmisor = retVal.rutEmisor;
            tipoDTE = retVal.tipoDTE;
            folioDTE = retVal.folioDTE;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.generaDTEResponse> generaDTEAsync(FacEleUtils.DoceleOLService.generaDTERequest request) {
            return base.Channel.generaDTEAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.obtieneDTEResponse FacEleUtils.DoceleOLService.DoceleOL.obtieneDTE(FacEleUtils.DoceleOLService.obtieneDTERequest request) {
            return base.Channel.obtieneDTE(request);
        }
        
        public int obtieneDTE(string rutEmisor, int tipoDTE, long folioDTE, FacEleUtils.DoceleOLService.obtieneDTEFormato formato, bool cedible, int cantidad, out string descripcionOperacion, out string XML, out byte[] PDF, out string URL) {
            FacEleUtils.DoceleOLService.obtieneDTERequest inValue = new FacEleUtils.DoceleOLService.obtieneDTERequest();
            inValue.rutEmisor = rutEmisor;
            inValue.tipoDTE = tipoDTE;
            inValue.folioDTE = folioDTE;
            inValue.formato = formato;
            inValue.cedible = cedible;
            inValue.cantidad = cantidad;
            FacEleUtils.DoceleOLService.obtieneDTEResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).obtieneDTE(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            XML = retVal.XML;
            PDF = retVal.PDF;
            URL = retVal.URL;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.obtieneDTEResponse> obtieneDTEAsync(FacEleUtils.DoceleOLService.obtieneDTERequest request) {
            return base.Channel.obtieneDTEAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.sinConfirmarResponse FacEleUtils.DoceleOLService.DoceleOL.sinConfirmar(FacEleUtils.DoceleOLService.sinConfirmarRequest request) {
            return base.Channel.sinConfirmar(request);
        }
        
        public int sinConfirmar(bool iniciaProceso, out string descripcionOperacion, out int cantidadDocumentos, out FacEleUtils.DoceleOLService.Documento[] Documento) {
            FacEleUtils.DoceleOLService.sinConfirmarRequest inValue = new FacEleUtils.DoceleOLService.sinConfirmarRequest();
            inValue.iniciaProceso = iniciaProceso;
            FacEleUtils.DoceleOLService.sinConfirmarResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).sinConfirmar(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            cantidadDocumentos = retVal.cantidadDocumentos;
            Documento = retVal.Documento;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.sinConfirmarResponse> sinConfirmarAsync(FacEleUtils.DoceleOLService.sinConfirmarRequest request) {
            return base.Channel.sinConfirmarAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.controversiaResponse FacEleUtils.DoceleOLService.DoceleOL.controversia(FacEleUtils.DoceleOLService.controversiaRequest request) {
            return base.Channel.controversia(request);
        }
        
        public int controversia(string rutEmisor, int tipoDTE, long folioDTE, FacEleUtils.DoceleOLService.controversiaOperacion operacion, out string descripcionOperacion) {
            FacEleUtils.DoceleOLService.controversiaRequest inValue = new FacEleUtils.DoceleOLService.controversiaRequest();
            inValue.rutEmisor = rutEmisor;
            inValue.tipoDTE = tipoDTE;
            inValue.folioDTE = folioDTE;
            inValue.operacion = operacion;
            FacEleUtils.DoceleOLService.controversiaResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).controversia(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.controversiaResponse> controversiaAsync(FacEleUtils.DoceleOLService.controversiaRequest request) {
            return base.Channel.controversiaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.obtieneBorradorResponse FacEleUtils.DoceleOLService.DoceleOL.obtieneBorrador(FacEleUtils.DoceleOLService.obtieneBorradorRequest request) {
            return base.Channel.obtieneBorrador(request);
        }
        
        public int obtieneBorrador(string rutEmisor, int tipoDTE, FacEleUtils.DoceleOLService.FormatoType formato, string txt, string xml, out string descripcionOperacion, out byte[] PDF) {
            FacEleUtils.DoceleOLService.obtieneBorradorRequest inValue = new FacEleUtils.DoceleOLService.obtieneBorradorRequest();
            inValue.rutEmisor = rutEmisor;
            inValue.tipoDTE = tipoDTE;
            inValue.formato = formato;
            inValue.txt = txt;
            inValue.xml = xml;
            FacEleUtils.DoceleOLService.obtieneBorradorResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).obtieneBorrador(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            PDF = retVal.PDF;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.obtieneBorradorResponse> obtieneBorradorAsync(FacEleUtils.DoceleOLService.obtieneBorradorRequest request) {
            return base.Channel.obtieneBorradorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacEleUtils.DoceleOLService.reimprimeDTEResponse FacEleUtils.DoceleOLService.DoceleOL.reimprimeDTE(FacEleUtils.DoceleOLService.reimprimeDTERequest request) {
            return base.Channel.reimprimeDTE(request);
        }
        
        public int reimprimeDTE(string rutEmisor, int tipoDTE, long folioDTE, out string descripcionOperacion) {
            FacEleUtils.DoceleOLService.reimprimeDTERequest inValue = new FacEleUtils.DoceleOLService.reimprimeDTERequest();
            inValue.rutEmisor = rutEmisor;
            inValue.tipoDTE = tipoDTE;
            inValue.folioDTE = folioDTE;
            FacEleUtils.DoceleOLService.reimprimeDTEResponse retVal = ((FacEleUtils.DoceleOLService.DoceleOL)(this)).reimprimeDTE(inValue);
            descripcionOperacion = retVal.descripcionOperacion;
            return retVal.estadoOperacion;
        }
        
        public System.Threading.Tasks.Task<FacEleUtils.DoceleOLService.reimprimeDTEResponse> reimprimeDTEAsync(FacEleUtils.DoceleOLService.reimprimeDTERequest request) {
            return base.Channel.reimprimeDTEAsync(request);
        }
    }
}
